{
 "title": "待完善数据",
 "tags": [ "TeslamateCustomDashboards" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "车辆",
    "query": "SELECT\n    id as __value,\n    CASE WHEN COUNT(id) OVER (PARTITION BY name) > 1 AND name IS NOT NULL THEN CONCAT(name, ' - ', RIGHT(vin, 6)) ELSE COALESCE(name, CONCAT('VIN ', vin)) end as __text \nFROM cars\nORDER BY display_priority ASC, name ASC, vin ASC;"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1"
   },
   {
    "name": "length_unit",
    "label": "长度单位",
    "query": "select unit_of_length from settings limit 1;"
   },
   {
    "name": "preferred_range",
    "query": "select preferred_range from settings limit 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "车辆信息 🚘",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  '车辆 ID: ' || id as id,\n  '名称: ' || name as name ,\n  'Model: ' || model as model,\n  '车架号: ' || vin as vin, \n  '颜色: ' || exterior_color as color,\n  '轮胎: '|| wheel_type,\n  '当前 ${preferred_range} 效率: ' || round((efficiency / convert_km(1, '$length_unit') * 1000)) || 'Wh/$length_unit' as efficiency\nFROM cars\nWHERE id = $car_id"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "#### 不完整数据\n从这里您可以检查是否有关于**行程** 和 **充电** 的不完整数据。如果存在，请参考官方指南：<a href='https://docs.teslamate.org/docs/maintenance/manually_fixing_data ' target='_blank'>手动修复数据</a>"
   }
  },
  {
   "title": "不完整行程 🛣️",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT id AS \"行程ID\", 开始, 结束, 距离, 最小持续时间 \nFROM drives \nWHERE car_id = $car_id AND end_date is null\nORDER BY start_date DESC"
    }
   ]
  },
  {
   "title": "不完整充电 ⚡",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT id as \"充电ID\", start_date, end_date, charge_energy_added, charge_energy_used, start_battery_level, end_battery_level, duration_min\nFROM charging_processes \nWHERE car_id = $car_id AND end_date is null\nORDER BY start_date DESC\n"
    }
   ]
  }
 ]
}